### ISSUE TITLE
Issue with playerloggedin?!?

### ISSUE THREAD

**Issue by NicosaurusRex99** [APengu/SolarFluxReborn#36] opened 2018-02-25 00:43 UTC
crash occurs on loadup
sf version 1.12.2-3.42r
https://pastebin.com/UDuVKLnd

**Comment by pinocchiowasjew** [comment] 2018-02-25 06:57
Ditto. The issue is caused by the newest version of Hammer Core (1.9.6.7). I suggest using 1.9.6.5 for now.

**Comment by APengu** [comment] 2018-02-25 11:37
Oki, fixed in 3.50r

**Closed by APengu** 2018-02-25 11:37 UTC
